# Generated by Django 6.0.5 on 2026-05-30 14:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Repository',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('path', models.CharField(max_length=1024, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'repositories',
                'indexes': [models.Index(fields=['name'], name='core_reposi_name_41e092_idx'), models.Index(fields=['is_active'], name='core_reposi_is_acti_c9e979_idx')],
            },
        ),
        migrations.CreateModel(
            name='ScanRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('scores', models.JSONField(default=dict)),
                ('gate', models.CharField(default='', max_length=10)),
                ('full_mode', models.BooleanField(default=False)),
                ('repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scans', to='core.repository')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='Finding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('layer', models.CharField(max_length=50)),
                ('severity', models.CharField(choices=[('CRITICAL', 'Critical'), ('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low'), ('INFO', 'Info')], max_length=20)),
                ('title', models.CharField(max_length=500)),
                ('file', models.CharField(blank=True, max_length=1024)),
                ('line', models.PositiveIntegerField(blank=True, null=True)),
                ('remediation', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('scan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='findings', to='core.scanrun')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='scanrun',
            index=models.Index(fields=['repository', 'started_at'], name='core_scanru_reposit_91c1a0_idx'),
        ),
        migrations.AddIndex(
            model_name='scanrun',
            index=models.Index(fields=['status'], name='core_scanru_status_11296e_idx'),
        ),
        migrations.AddIndex(
            model_name='finding',
            index=models.Index(fields=['scan', 'severity'], name='core_findin_scan_id_d819d6_idx'),
        ),
        migrations.AddIndex(
            model_name='finding',
            index=models.Index(fields=['layer'], name='core_findin_layer_2d9942_idx'),
        ),
    ]
