# Generated by Django 6.0.5 on 2026-06-01 21:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scans_used', models.PositiveIntegerField(default=0)),
                ('scans_limit', models.PositiveIntegerField(default=50)),
                ('paid', models.BooleanField(default=False)),
                ('stripe_customer_id', models.CharField(blank=True, max_length=255)),
                ('stripe_subscription_id', models.CharField(blank=True, max_length=255)),
                ('figma_token', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveIndex(
            model_name='scanrun',
            name='core_scanru_reposit_91c1a0_idx',
        ),
        migrations.AddField(
            model_name='scanrun',
            name='figma_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='scanrun',
            name='report_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='scanrun',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scans', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='scanrun',
            name='repository',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scans', to='core.repository'),
        ),
        migrations.AddIndex(
            model_name='scanrun',
            index=models.Index(fields=['user', 'started_at'], name='core_scanru_user_id_54f9c2_idx'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
